= RP-OOO3-FCC "Follow Christ to the Cross"
- v1.0, 2020-08-01 Ernest Prabhakar <admin+operator@igwet.com>

== USAGE

- WHEN there does not seem to be any honorable way forward,
- TRY denying Self to follow Christ all the way to the cross
- SO THAT we and our reality can be transformed in His image

== DETAILS

Successful cultures include mechanisms to tie short-term self-interest to the long-term needs of the community.
The most powerful such mechanism is a _worldview_, which shapes our perceptions of identity, morality, and reality.
Not only does worldview affect our conscious notions of right and wrong, it subtly constrains what we find possible, or even thinkable.

When we start following Jesus, it is because of desires present in our personal or cultural worldview.
Those desires might not in themselves be good or bad.
But if we follow Him long enough -- and hard enough -- He eventually asks us to choose between those desires and complete obedience.
As He Himself did at Gethsemene.

Do we only follow Jesus because of what He can give us?
Or do we follow Jesus so we can give him our everything?

Those of us from an evangelical background are used to this happening at conversion.
The next challenge  is about learning do that repeatedly as a community.
Because that is the only way we can succeed at helping each other accomplish *everything* He told us to do.

== EXAMPLE

Like many men, I (Ernie) have struggled with an addiction to pornography.
What is perhaps unusual is that I:

a. Only started in my twenties, _after_ I had successfully completed every discipleship program I could find (and still found myself single, and desperately lonely)
b. Experienced the most temptation right _after_ spiritual events, such as our Thursday night College & Career group
c. Felt the most self-hatred when I _resisted_ temptation; which was even worse than the "ordinary" shame of giving in.

When I finally asked for therapy to deal with this addiction, my pastor had me write a letter to my "inner child" from my older, wiser self.
This tapped into a deep well of pain and anger, which eventually enable me to reconciled with myself.

The surprise twist, however, was discovering that "older, wiser me" was just as artificial and shallow as my "inner child!"
I had to die to everything I thought I was and had accomplished, in order to uncover deeper layers of my identity.
And then discover new ways to submit those new identities to the Lordship of Christ.

Eventually, after many false starts, my addiction to pornography was healed by a powerful encounter with God as a Father taking dominion over my sexuality, and my shame.
However, that encounter only broke the _addiction_; I still experienced (and occasionally gave into) _temptation_.
Surprisingly, the practice that eventually enabled me to overcome temptation appears to have been Entrepreneurship.
But that is another story for another time.

== PRIOR ART
- Two Trees
- The War of Art, Review (Derek Sivers)
- Peter rebukes Jesus


- https://en.wikipedia.org/wiki/Benedictines[Benedictine] monastic movement
- https://en.wikipedia.org/wiki/Disruptive_innovation[Disruptive Innovation]
- The Early Church in https://www.biblegateway.com/passage/?search=Acts+2%3A40-47&version=NIV[Acts 2]
- Jesus https://en.wikipedia.org/wiki/Calling_of_the_disciples[calling the disciples]
- http://theleanstartup.com/principles[Lean Startup] and https://medium.com/west-stringfellow/go-to-market-the-lean-startup-mvps-and-product-market-fit-a0d61574dde9[Minimum Viable Product]
- https://www.python.org/dev/peps/pep-0001/[Python Enhancement Proposals]
